#!/bin/bash

#VARIAVEIS NO SHELL

funcao01(){

	echo "LISTAR ARQUIVOS"
	echo "$1"
}

echo "(`funcao01 teste`)"

echo "ARGUMENTOS DE LINHA DE COMANDO:$#"
echo "ARGUMENTOS FORNECIDOS NA LINHA DE COMANDO: $-"
echo "SAIDA DO ULTIMO COMANDO EXECUTADO: $?"
echo "PROCESSOS ATIVOS: $$"
echo "PROCESSOS DO ULTIMO COMANDO EM SEGUNDO PLANO: $!"
echo "PRIMEIRA PALAVAR/NOME DO COMANDO: $0"


