/* INSERIR 2 REGISTROS NOVOS */
    INSERT INTO TABALUNOS (MATRICULA,NOME,CURSO) VALUES    (NULL,'GILBERTO','ADS');

 /*INCLUIR 1 REGISTRO 'INTO TABALUNOS COM VALUES' */
   INSERT INTO TABALUNOS (NOME,SEXO,DATANASC,NOTA1) VALUES ('MARTA SOUZA','F','2000-01-10',9.0);
   
2) /* INCLUIR 1 REGISTRO  INTO 'TABALUNOS COM SETS' */
  INSERT INTO TABALUNOS SET NOME='ERICA MENDES',SEXO='F';
  INSERT INTO TABALUNOS SET NOME='DEISE CARVALHO',SEXO='F';

3) /* ALTERAR NOTA1 PARA 10.0 E DATA DE NASCIMENTO = '1998-10-10' DA MATRICULA 1 */
 UPDATE TABALUNOS SET NOTA1=10.0,DATANASC='1998-10-10' WHERE MATRICULA=1;
