/* 1 - MOSTRAR A QTD DE REGISTRO DA TABELA TABALUNOS 
SELECT COUNT(nome) FROM tabalunos; */

/* 2 - MOSTRAR QDT DE ALUNOS DO CURSO SEG TABALUNOS 
SELECT COUNT(nome) FROM tabalunos WHERE curso = 'SEG'; */

/* 3 - MOSTRAR NOME E DATANASC NO FORMATO DD/MM/AAAA 
SELECT nome, DATE_FORMAT(datanasc, '%d/%m/%Y') FROM tabalunos;*/

/* 4 - QUAL O MAIOR COMPRIMENTO DO NOME 
SELECT MAX(nome) FROM tabalunos;*/

/* 5 - MOSTRE NOME.DATANASC E IDADE(PRECISA CALCULAR) 
SELECT nome, CAST( (TO_DAYS(NOW())- TO_DAYS(datanasc)) / 365 as SIGNED) AS idade  FROM tabalunos; */

/* 6 - MOSTRE A MATRICULA E NOME E SENHA PROVISORIA(NOME EM MINUSCULA AO CONTRARIO SEM ESPACOS 
SELECT matricula, nome, UPPER(REVERSE(nome)) FROM tabalunos;*/

/* 7 - MOSTRE NOME,DATANASC E A DATA DO BATIZADO, SABENDO QUE O BATIZADO OCORREU 45 DIAS APOS O NASCIMENTO 
SELECT nome, datanasc, DATE_ADD(datanasc, INTERVAL 45 DAY) AS batismo FROM tabalunos;*/

/* 8 - MOSTRE O TOTAL DE ALUNOS POR CURSO */
SELECT DISTINCT 
(SELECT COUNT(*) from tabalunos WHERE curso = 'SEG') as SEGURANCA,
(SELECT COUNT(*) from tabalunos WHERE curso = 'ADS') as ANALISE_E_DESENV_DE_SISTEMAS,
(SELECT COUNT(*) from tabalunos WHERE curso = 'SEG') as COMEX;




/* 9 - MOSTRE A MATRICULA,NOTA1,NOTA2 E MEDIA(PRECISA CALCULAR COM 2 CASAS DECIMAIS) */


/* 10 - MOSTRE A MAIOR MEDIA DAS NOTAS POR CURSO */


/* 11 - MOSTRE A MEDIA DAS NOTA1 POR CURSO DESDE QUE O CURSO TENHA MAIS DE 1 ALUNO */


/* 12 - MOSTRE A DATA DE NASCIMENTO DO ALUNO MAIS VELHO */


/* 13 - MOSTRE NOME E IDADE EM ORDEM DECRESCENTES(IDADE) */


/* 14 - MOSTRE O TOTAL DE ALUNOS DO CURSO DE ADS */


/* 15 - MOSTRE O PRIMEIRO NOME DOS ALUNOS */


/* 16 - MOSTRE O TOTAL DE ALUNOS POR ANO DE NASCIMENTO */


/* 15 -MOSTRE O PRIMEIRO NOME DOS ALUNOS */


/* 16 - MOSTRE O TOTAL DE ALUNOS POR ANO DE NASCIMENTO */


/* 17 - MOSTRE O NRO DE ANIVERSARIANTES DO MES */


/* 18- QUANTOS ALUNOS NASCERAM ENTRE JANEIRO E JUNHO */


/* 19 - MOSTRE A MEDIA DAS MEDIAS POR SEXO */


/* 20 - MOSTRE QUANTOS ALUNOS COMECAM O NOME COM VOGAL */

