/* SCRIPT DA CRIACAO DO BANCO DE DADOS CONSULTORIO */
CREATE DATABASE Consultorio;

/*conecta ao banco consultorio*/
USE Consultorio;

/*criacao da tabela Convenio */

CREATE TABLE CONVENIO(
   CODCONV INT AUTO_INCREMENT PRIMARY KEY,
   NOMECONVenio VARCHAR(30) NOT NULL,
   FONECON CHAR(12)
);

/*criacao da tabela paciente */

CREATE TABLE PACIENTE(
   IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
   NOMEPAC VARCHAR(40) NOT NULL,
   SEXO CHAR(1) DEFAULT 'F',
   DATANASC DATE,
   FONE CHAR(12),
   CODCONV INT,
   FOREIGN KEY(CODCONV) REFERENCES
           CONVENIO(CODCONV)
);
   
/*criacao da tabela de especialidade*/

CREATE TABLE ESPECIALIDADE(
  CODESPEC INT AUTO_INCREMENT PRIMARY KEY,
  NOMEESPEC VARCHAR(20) NOT NULL
);

/*criacao da tabela de medico*/

CREATE TABLE MEDICO(
   IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
   NOMEMED VARCHAR(40) NOT NULL,
   sexo char(1) default 'm',
   CRM NUMERIC(8) NOT NULL,
   CODESPEC INT,
   FOREIGN KEY (CODESPEC) REFERENCES
     ESPECIALIDADE(CODESPEC)
);

/*criacao da tabela consulta */

CREATE TABLE CONSULTA(
    IDPACIENTE INT,
    IDMEDICO INT,
    DATACONS DATE,
    QUEIXA VARCHAR(100),
    PRESCRICAO VARCHAR(100),
    PRIMARY KEY(IDPACIENTE,IDMEDICO,DATACONS),
    FOREIGN KEY (IDPACIENTE) REFERENCES
             PACIENTE(IDPACIENTE),
    FOREIGN KEY (IDMEDICO) REFERENCES
             MEDICO(IDMEDICO)
);  

/*DADOS CONSULTORIO*/

INSERT INTO CONVENIO VALUES
(NULL, 'SUL AMERICA', 6012378),
(NULL,'SAUDE TOTAL',999098),
(NULL,'GOOD HEALTH',776544);

INSERT INTO PACIENTE VALUES
(NULL, 'JOAO DA SILVA','M', '1998-10-10',5566667,1),
(NULL,'VERA RODRIGUES','F', '1992-08-10',5543211,2),
(NULL,'PAULO RANGEL','M','1990-04-12', 8874662, 3);

INSERT INTO ESPECIALIDADE (NOMEESPEC)
 VALUES('CLINICA GERAL'), ('ORTOPEDIA');

INSERT INTO MEDICO VALUES
(NULL,'PAULO','M',50345,1),
(NULL,'MARINA','F',12345,2);

INSERT INTO CONSULTA VALUES
(1,1,CURDATE(),'DOR DE CABECA','ANALGESICO'),
(1,2,CURDATE(),'DOR NAS COSTAS','RAIO X'),
(2,1,CURDATE(),'AZIA','OMEPRAZOL');
