algoritmo "9.	Criar e carregar uma matriz [4][4] com valores aleatórios, sendo que a diagonal principal terá seus dados carregados no programa segundo:
1 - 4 - 16 - 64"
//precisa fazer com que a diagonal seja o matriz [2,2] ao quadrado, ou ao cubo
// matriz [1,1] = 1
var
//matriz [i,j]
//se i = j, numero naquela posição será matriz[2,2] elevado a i ou j - 1
// exemplo : se matriz[2,2] = 5, matriz[3,3] será matriz[2,2]^i-1, sendo i = 2
inicio
// Seção de Comandos
fimalgoritmo
